version: "3"
services:
  node-app:
    container_name: node-app
    restart: always
    depends_on:
      - mongo
    build: .
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - db:/data/db
    env_file: ./.env
    ports:
      - $MONGO_LOCAL_PORT:$MONGO_DOCKER_PORT
  
volumes:
  db: