version: "3"
services:
  node-app:
    container_name: docker-node
    restart: always
    depends_on:
      - mongo
    build: .
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - db:/data/db
    env_file: ./.env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
  
volumes:
  db: